[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "liman_core"
dynamic = ["version"]
description = "Liman AgentOps Core Library"
readme = "README.md"
license = "MIT"
requires-python = ">=3.10"
authors = [
    { name = "Guro Bokum", email = "jiojiajiu@gmail.com" }
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "dishka>=1.6.0",
    "langchain-core>=0.3.67",
    "lark>=1.2.2",
    "liman-finops[finops]",
    "pydantic>=2.11.7",
    "rich>=14.0.0",
    "ruamel-yaml>=0.18.14",
]

[tool.hatch.version]
path = "VERSION"
pattern = "(?P<version>.+)"

[tool.hatch.build.targets.sdist]
include = [
    "/src",
    "/README.md",
    "/VERSION",
]

[tool.poe]
include = "../../shared_poe.toml"

[tool.poe.tasks]
mypy = "mypy --config-file ../../pyproject.toml ."

[tool.ruff]
extend = "../../pyproject.toml"

[tool.mypy]
extend = "../../pyproject.toml"

[tool.uv.sources]
liman-finops = { workspace = true }

[dependency-groups]
dev = [
    "typing-extensions>=4.14.0",
]
