[tool.uv.sources]
liman = { workspace = true }
liman_core = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

[dependency-groups]
dev = [
    "mypy>=1.16.0",
    "poethepoet>=0.35.0",
    "pytest>=8.4.0",
    "pytest-cov>=6.2.1",
    "ruff>=0.11.13",
]

[tool.poe.tasks]
lint = ["_format", "_lint"]
format = "ruff format"
mypy = "mypy ."
test = "pytest"
_format = "ruff format --check"
_lint = "ruff check --diff"


[tool.ruff]
# https://docs.astral.sh/ruff/configuration
line-length = 88 # default
indent-width = 4

[tool.ruff.lint]
extend-select = ["B", "I", "SIM", "UP"]
ignore = ["F401"]

[tool.ruff.format]
indent-style = "space"
docstring-code-format = true

[tool.mypy]
# https://mypy.readthedocs.io/en/latest/config_file.html
strict = true
strict_optional = true
show_error_codes = true
show_column_numbers = true
implicit_reexport = false
disallow_any_unimported = false
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_no_return = true
warn_return_any = true
warn_unused_configs = true
strict_equality = true
exclude = []

[tool.pytest.ini_options]
asyncio_mode = "auto"
env_override_existing_values = 1
