[tool.uv.sources]
liman = { workspace = true }
liman_core = { workspace = true }
liman_finops = { workspace = true }
liman_openapi = { workspace = true }
proto = { path = "./proto" }

[tool.uv.workspace]
members = ["packages/*"]

[dependency-groups]
dev = [
    "mypy>=1.16.0",
    "poethepoet>=0.35.0",
    "pytest>=8.4.0",
    "pytest-asyncio>=0.25.0",
    "pytest-cov>=6.2.1",
    "pytest-dotenv>=0.5.2",
    "ruff>=0.11.13",
]

[tool.poe.tasks]
typing.sequence = [
  { cmd = "poe mypy", cwd = "packages/liman" },
  { cmd = "poe mypy", cwd = "packages/liman_core" },
  { cmd = "poe mypy", cwd = "packages/liman_finops" },
  { cmd = "poe mypy", cwd = "packages/liman_openapi" }
]
lint.sequence = [
  { cmd = "poe lint", cwd = "packages/liman" },
  { cmd = "poe lint", cwd = "packages/liman_core" },
  { cmd = "poe lint", cwd = "packages/liman_finops" },
  { cmd = "poe lint", cwd = "packages/liman_openapi" }
]
protoc = "protoc --python_out=proto/  --proto_path=../proto --pyi_out=proto/ liman.proto"


[tool.ruff]
# https://docs.astral.sh/ruff/configuration
line-length = 88 # default
indent-width = 4
respect-gitignore = true

[tool.ruff.lint]
extend-select = ["B", "I", "SIM", "UP"]

[tool.ruff.format]
indent-style = "space"
docstring-code-format = true

[tool.mypy]
# https://mypy.readthedocs.io/en/latest/config_file.html
strict = true
strict_optional = true
show_error_codes = true
show_column_numbers = true
implicit_reexport = false
disallow_any_unimported = false
disallow_any_generics = true
disallow_subclassing_any = true
disallow_untyped_calls = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_no_return = true
warn_return_any = true
warn_unused_configs = true
strict_equality = true
mypy_path = "$MYPY_CONFIG_FILE_DIR"
exclude_gitignore = true

[[tool.mypy.overrides]]
module = ["wrapt.*"]
ignore_missing_imports = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
env_override_existing_values = 1
