[tool.poe.tasks]
lint.sequence = [
  { cmd = "ruff format --check" },
  { cmd = "ruff check --diff" }
]
format = "ruff format"
test = "pytest"
coverage = "pytest --cov --cov-report=xml --cov-report=term"
