name: Python Checks

on:
  push:
    branches:
      - main
    paths:
      - python/**
      - .github/workflows/python-*.yaml
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: ./python

jobs:
  lint:
    name: Lint ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - liman
          - liman_core
          - liman_finops
          - liman_openapi
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.package }}
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
      - name: Install dependencies
        run: |
          uv sync --locked --all-extras
      - name: Compile Protobuf files
        run: |
          uv run poe protoc
      - name: Run ruff
        run: |
          uv run poe -C packages/${{ matrix.package }} lint
      - name: Run mypy
        run: |
          uv run poe -C packages/${{ matrix.package }} mypy

  test:
    name: Test ${{ matrix.package }}-${{ matrix.python-version }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
        package:
          - liman
          - liman_core
          - liman_openapi
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.package }}-${{ matrix.python-version }}-${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install protoc
        run: |
          sudo apt-get update
          sudo apt-get install -y protobuf-compiler
      - name: Install dependencies
        run: |
          uv sync --locked --all-extras
      - name: Compile Protobuf files
        run: |
          uv run poe protoc
      - name: Run tests
        run: |
          uv run poe -C packages/${{ matrix.package }} test
