name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      python/packages/liman_core--release_created: ${{ steps.release-please.outputs['python/packages/liman_core--release_created'] }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release-please
      - name: Show release outputs
        run: |
          echo "release_created: ${{ steps.release-please.outputs['python/packages/liman_core--release_created'] }}"

  release-py-liman-core:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs['python/packages/liman_core--release_created'] == 'true' }}
    defaults:
      run:
        working-directory: python/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Compile Protobuf files
        run: |
          uv run poe protoc
      - run: uv build --package liman_core --out-dir dist/
      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python/dist/
